export const SET_FILTERS = 'SET_FILTERS'
export const SEARCH_POKEMONS = "SEARCH_POKEMONS"
export const DISPLAY_POKEMONS = "DISPLAY_POKEMONS"
export const CHANGE_DISPLAY_MODE = 'CHANGE_DISPLAY_MODE'
export const CHANGE_START_POSITION = 'CHANGE_START_POSITION'
export const SET_ALL_POKEMONS_DATA = "SET_ALL_POKEMONS_DATA"
export const SET_POKEMONS_BY_TYPES = "SET_POKEMONS_BY_TYPES"
