export const SET_POKEMONS = "SET_POKEMONS"
export const SEARCH_POKEMONS = "SEARCH_POKEMONS"
export const DISPLAY_POKEMONS = "DISPLAY_POKEMONS"
export const CHANGE_DISPLAY_MODE = 'CHANGE_DISPLAY_MODE'
export const CHANGE_START_POSITION = 'CHANGE_START_POSITION'
export const SET_ALL_POKEMONS_DATA = "SET_ALL_POKEMONS_DATA"
